### ISSUE TITLE
Internal error: Call to undefined method PHPStan\Type\ObjectType::getValue() while analysing file

### ISSUE THREAD

**Issue by Afrowson** [larastan/larastan#2076]
- Larastan Version: 2.9.9
- Laravel Version: 11.28.1

### Description
This is happening while upgrading to Laravel 11:
I cast Enums from the DB in to PHP Enums, if i do not annotate, i get warnings for trying to  calling a method on string. If i do annotate like the following, as described in [here](https://github.com/larastan/larastan/blob/2.x/UPGRADE.md#upgrading-to-296-from-295). My guess is that the detection of casts in to PHP Classes instead of basic types like array/int/string is not working correctly.

adding an old fashion style class `@property` annotation still works, but it would be nice if it couldd be detected from the array it self. 

### Laravel code where the issue was found
```php
    /**
     * @return array{ background_position:  ImagePosition, background_size:  ImageSize, background_repeat:  ImageRepeat, font_stack:  DesignFontStack }
     */
    protected function casts(): array
    {
        return [
            'background_position' => ImagePosition::class,
            'background_size' => ImageSize::class,
            'background_repeat' => ImageRepeat::class,
            'font_stack' => DesignFontStack::class,
        ];
    }
```

```
## /var/www/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(261)                                                                                        
#0 [internal function]: Larastan\Larastan\Properties\ModelCastHelper::Larastan\Larastan\Properties\{closure}()                                                      
#1 /var/www/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(261): array_map()                                                                           
#2 /var/www/vendor/larastan/larastan/src/Properties/ModelCastHelper.php(225): Larastan\Larastan\Properties\ModelCastHelper->getModelCasts()                         
#3 /var/www/vendor/larastan/larastan/src/Properties/ModelPropertyHelper.php(119): Larastan\Larastan\Properties\ModelCastHelper->getCastForProperty()                
#4 /var/www/vendor/larastan/larastan/src/Properties/ModelPropertyExtension.php(30): Larastan\Larastan\Properties\ModelPropertyHelper->getDatabaseProperty()         
#5 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(656): Larastan\Larastan\Properties\ModelPropertyExtension->getProperty()  
#6 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(188): PHPStan\Reflection\ClassReflection->getProperty()                              
#7 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Type/IntersectionType.php(412): PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype()                
#8 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Type/IntersectionType.php(403): PHPStan\Type\IntersectionType->getUnresolvedPropertyPrototype()          
#9 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3988): PHPStan\Type\IntersectionType->getProperty()                           
#10 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3995): PHPStan\Analyser\MutatingScope->getPropertyReflection()               
#11 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1702): PHPStan\Analyser\MutatingScope->propertyFetchType()                   
#12 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1708): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()          
#13 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(617): PHPStan\Analyser\MutatingScope->resolveType()                          
#14 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3031): PHPStan\Analyser\MutatingScope->getType()                             
#15 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3112): PHPStan\Analyser\MutatingScope->removeTypeFromExpression()            
#16 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3048): PHPStan\Analyser\MutatingScope->filterBySpecifiedTypes()              
#17 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1534): PHPStan\Analyser\MutatingScope->filterByTruthyValue()                 
#18 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(617): PHPStan\Analyser\MutatingScope->resolveType()                          
#19 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1545): PHPStan\Analyser\MutatingScope->getType()                             
#20 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(617): PHPStan\Analyser\MutatingScope->resolveType()                          
#21 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(843): PHPStan\Analyser\MutatingScope->getType()                              
#22 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(617): PHPStan\Analyser\MutatingScope->resolveType()                          
#23 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1798): PHPStan\Analyser\MutatingScope->getType()                         
#24 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(724): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr()     
#25 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode()              
#26 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1146): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                
#27 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(617): PHPStan\Analyser\MutatingScope->resolveType()                          
#28 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ParametersAcceptorSelector.php(228): PHPStan\Analyser\MutatingScope->getType()               
#29 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1775): PHPStan\Reflection\ParametersAcceptorSelector::selectFromArgs()       
#30 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(617): PHPStan\Analyser\MutatingScope->resolveType()                          
#31 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.php(52): PHPStan\Analyser\MutatingScope->getType()                        
#32 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/ReturnTypeRule.php(55): PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType()          
#33 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(120): PHPStan\Rules\Methods\ReturnTypeRule->processNode()                     
#34 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(119): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()      
#35 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(653): PHPStan\Node\ClassStatementsGatherer->__invoke()                   
#36 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(534): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()   
#37 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode()              
#38 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(652): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()             
#39 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode()              
#40 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(789): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()             
#41 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode()              
#42 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(759): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()             
#43 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(429): PHPStan\Analyser\NodeScopeResolver->processStmtNode()              
#44 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(179): PHPStan\Analyser\NodeScopeResolver->processNodes()                      
#45 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(139): PHPStan\Analyser\FileAnalyser->analyseFile()                            
#46 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                                                  
PHPStan\Command\WorkerCommand::PHPStan\Command\{closure}()                                                                                                          
#47 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_eb6a95a92\Evenement\EventEmitter->emit()            
#48 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                                                  
_PHPStan_eb6a95a92\Clue\React\NDJson\Decoder->handleData()                                                                                                          
#49 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_eb6a95a92\Evenement\EventEmitter->emit()                     
#50 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                                                  
_PHPStan_eb6a95a92\React\Stream\Util::_PHPStan_eb6a95a92\React\Stream\{closure}()                                                                                   
#51 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(168): _PHPStan_eb6a95a92\Evenement\EventEmitter->emit()    
#52 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                                      
_PHPStan_eb6a95a92\React\Stream\DuplexResourceStream->handleData()                                                                                                  
#53 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                                      
_PHPStan_eb6a95a92\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                                                                        
#54 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(99): _PHPStan_eb6a95a92\React\EventLoop\StreamSelectLoop->run()               
#55 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()                   
#56 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):                                                                
_PHPStan_eb6a95a92\Symfony\Component\Console\Command\Command->run()                                                                                                 
#57 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261):                                                                
_PHPStan_eb6a95a92\Symfony\Component\Console\Application->doRunCommand()                                                                                            
#58 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):                                                                
_PHPStan_eb6a95a92\Symfony\Component\Console\Application->doRun()                                                                                                   
#59 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(127): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->run()                           
#60 phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(128): _PHPStan_eb6a95a92\{closure}()                                                            
#61 /var/www/vendor/phpstan/phpstan/phpstan(8): require('...')                                                                                                      
#62 /var/www/vendor/bin/phpstan(119): include('...')                                                                                                                
#63 {main}           
```

**Comment by canvural** [comment]
Hi,

Yeah, the crash should not happen. That should be fixed. But your return annotation should be like `@return array{ background_position:  'App\FullyQualifedName\ImagePosition' ...`

**Comment by Afrowson** [comment]
Yea i got that after trying for a while...

```php
    /**
     * @return array{
     *     background_position:  'App\Models\Enums\ImagePosition',
     *     background_size:  'App\Models\Enums\ImageSize',
     *     background_repeat:  'App\Models\Enums\ImageRepeat',
     *     font_stack:  'App\Models\Enums\DesignFontStack'
     *     }
     */
    protected function casts(): array
    {
        return [
            'background_position' => ImagePosition::class,
            'background_size' => ImageSize::class,
            'background_repeat' => ImageRepeat::class,
            'font_stack' => DesignFontStack::class,
        ];
    }
```

works, nice! 

But i think it is still flawed and not really how it should work. 

this works as well:
```php
    /**
     * @return array{
     *     date:  'immutable_date:Y-m-d',
     *     from:  'immutable_datetime:H:i',
     *     until:  'immutable_datetime:H:i'
     *     }
     */
    protected function casts(): array
    {
        return [
            'date' => 'immutable_date:Y-m-d',
            'from' => 'immutable_datetime:H:i',
            'until' => 'immutable_datetime:H:i',
        ];
    }
    
```
But then i get this error:  
```
  ------ --------------------------------------------------- 
  Line   Http/Controllers/Nova/EventTimeSlotController.php  
 ------ --------------------------------------------------- 
  72     Cannot call method setISODate() on string.         
  78     Cannot access property $dayOfWeek on string.       
 ------ --------------------------------------------------- 
```

for this code: 
`... $timeSlot->date->setISODate(...)...`

if i set this:
```php
    /**
     * @return array{
     *     date: '\DateTimeInterface',
     *     from: '\DateTimeInterface',
     *     until: '\DateTimeInterface',
     *     }
     */
    protected function casts(): array
    {
        return [
            'date' => 'immutable_date:Y-m-d',
            'from' => 'immutable_datetime:H:i',
            'until' => 'immutable_datetime:H:i',
        ];
    }
```

I get an Error for the return type of the array... 

 ```
 Method App\Models\EventTimeSlot::casts() should return array{date: '\\DateInterface', from: '\\DateTimeInterface', until: '\\DateTimeInterface'} but returns  
         array{date: 'immutable_date:Y-m-d', from: 'immutable_datetime…', until: 'immutable_datetime…'}.                                                               
         💡 Offset 'date' ('\\DateInterface') does not accept type 'immutable_date:Y-m-d'.   
```

I understand that this is wrong for the array... but it would be correct for the Laravel Model Cast resulting attribute... it is not a string.

**Comment by LWlook** [comment]
Had the same error. This helped me because i didn't know i had to type the full class string for the doctype.
But it is a lot of work to write every cast two times because larastan needs it in a doctype...

**Comment by calebdw** [comment]
See #1878, your only other option is to use the `$casts` property

**Comment by sebastiaanluca** [comment]
> Hi,
> 
> Yeah, the crash should not happen. That should be fixed. But your return annotation should be like `@return array{ background_position: 'App\FullyQualifedName\ImagePosition' ...`

In my case that didn't fix it, the error persists. Anything else I can try to debug?

```php
    /**
     * @return array{id: 'integer', group: \Domain\Media\Enums\TemporaryFileUploadGroup, session_id: 'string',
     *     created_at: 'immutable_datetime', updated_at: 'immutable_datetime'}
     */
```

Neither works:
- `\Domain\Media\Enums\TemporaryFileUploadGroup`
- `Domain\Media\Enums\TemporaryFileUploadGroup`
- `TemporaryFileUploadGroup`

**Comment by calebdw** [comment]
The generics above the `casts()` method are no longer needed on my published fork: https://github.com/calebdw/larastan

 #2197 would also allow remove the need for generics.

However, to answer your question, you should have:


```php
    /**
     * @return array{id: 'integer', group: 'Domain\\Media\\Enums\\TemporaryFileUploadGroup', session_id: 'string',
     *     created_at: 'immutable_datetime', updated_at: 'immutable_datetime'}
     */
```

**Comment by canvural** [comment]
This is fixed in newer releases of Larastan.
